# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd4de88350ee4485b7441a59fed477769866e3ee4e13c6b830348d1258ab7218020b4a383a34586221188304014c6ca973c0a136bb86e095d49c1c635cde159

test:
  secret_key_base: a57c4f8644bd73483d99c2ffd4ff741d459e1100d15792a0a26a67e19f9d9a5e3442a77f80bb85a01b1ca5c369446d52806135fb70182ee464468bd9c8c3f8f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
